import os
import json
from config import DOCUMENTS_DIR, TRAINING_DATA_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR

SAMPLE_DOCUMENTS = [
    {
        "filename": "ai_notes.txt",
        "content": (
            "Artificial Intelligence (AI) is the simulation of human intelligence processes by computer systems. "
            "These processes include learning, reasoning, problem solving, perception, and self-correction. "
            "Specific applications of AI include expert systems, speech recognition, machine translation, and computer vision. "
            "Artificial General Intelligence (AGI) refers to hypothetical machines possessing human-level cognitive capabilities across all domains. "
            "Narrow AI or weak AI is designed to perform a dedicated single task such as image classification or chess playing."
        )
    },
    {
        "filename": "machine_learning_overview.txt",
        "content": (
            "Machine Learning (ML) is a subfield of artificial intelligence that focuses on building algorithms that learn patterns from data. "
            "Instead of being explicitly programmed with static rules, ML algorithms construct statistical models from sample training data. "
            "Supervised learning algorithms build predictive models from labeled datasets with known target outputs. "
            "Unsupervised learning discovers hidden patterns, clusters, and representations in unlabeled data without target labels. "
            "Reinforcement learning trains autonomous agents to make sequences of decisions by maximizing cumulative rewards in an environment."
        )
    },
    {
        "filename": "transformer_architecture.txt",
        "content": (
            "The Transformer architecture was introduced in the seminal 2017 paper 'Attention Is All You Need' by Vaswani et al. "
            "Transformers replace recurrent neural networks (RNNs) and LSTM networks with multi-head self-attention mechanisms. "
            "This enables parallel computation across all tokens in a sequence, eliminating the sequential bottleneck of recurrence. "
            "Key components include Scaled Dot-Product Attention, Sinusoidal Positional Encodings, Feed-Forward Networks, and Residual Layer Normalization. "
            "Transformers form the foundational backbone for modern Large Language Models, BERT, GPT, and Retrieval-Augmented Generation systems."
        )
    },
    {
        "filename": "rag_systems.txt",
        "content": (
            "Retrieval-Augmented Generation (RAG) is an architectural framework that enhances Large Language Models by retrieving relevant documents from an external knowledge base. "
            "A standard RAG pipeline consists of document ingestion, text chunking, dense vector embedding, similarity search in a vector database, and prompt-conditioned answer generation. "
            "RAG significantly reduces model hallucination, ensures grounding in authoritative source documents, and provides verifiable citations. "
            "Dense retrievers use dual encoder neural networks trained with InfoNCE contrastive loss to map questions and passages into a shared vector space."
        )
    },
    {
        "filename": "deep_learning_concepts.txt",
        "content": (
            "Deep Learning is a branch of machine learning based on artificial neural networks with multiple representation layers. "
            "Backpropagation and gradient descent are used to optimize network weights by minimizing a loss function. "
            "Common activation functions include ReLU, GELU, and Sigmoid, which introduce non-linearity into neural representations. "
            "Layer Normalization stabilizes the hidden state dynamics in deep Transformers and accelerates training convergence."
        )
    },
    {
        "filename": "vector_databases.txt",
        "content": (
            "Vector databases store high-dimensional dense vector embeddings generated by neural embedding models. "
            "They enable fast nearest-neighbor similarity search using metrics such as Cosine Similarity, Dot Product, and Euclidean Distance. "
            "In a local RAG system, document chunks are indexed as dense vectors, allowing the retriever to identify relevant context in milliseconds."
        )
    }
]

SAMPLE_RETRIEVER_DATA = [
    {
        "question": "What is Artificial Intelligence?",
        "positive_doc": "Artificial Intelligence (AI) is the simulation of human intelligence processes by computer systems, including learning and reasoning.",
        "negative_doc": "The capital of France is Paris and it is known for the Eiffel Tower and art museums."
    },
    {
        "question": "What is Machine Learning?",
        "positive_doc": "Machine Learning (ML) is a subfield of artificial intelligence that focuses on building algorithms that learn patterns from data.",
        "negative_doc": "Photosynthesis is the chemical process used by green plants to convert light energy into chemical energy."
    },
    {
        "question": "Who introduced the Transformer architecture?",
        "positive_doc": "The Transformer architecture was introduced in the seminal 2017 paper Attention Is All You Need by Vaswani et al.",
        "negative_doc": "Water freezes at zero degrees Celsius and boils at one hundred degrees Celsius under atmospheric pressure."
    },
    {
        "question": "What are the core components of RAG?",
        "positive_doc": "A standard RAG pipeline consists of document ingestion, chunking, dense vector embedding, similarity search, and answer generation.",
        "negative_doc": "The Pythagorean theorem states that a squared plus b squared equals c squared in a right triangle."
    },
    {
        "question": "What is supervised learning?",
        "positive_doc": "Supervised learning algorithms build predictive models from labeled datasets with known target outputs.",
        "negative_doc": "William Shakespeare wrote the tragedy Hamlet in the early seventeenth century in England."
    },
    {
        "question": "What is unsupervised learning?",
        "positive_doc": "Unsupervised learning discovers hidden patterns, clusters, and representations in unlabeled data without target labels.",
        "negative_doc": "The speed of light in a vacuum is approximately three hundred thousand kilometers per second."
    },
    {
        "question": "What is reinforcement learning?",
        "positive_doc": "Reinforcement learning trains autonomous agents to make sequences of decisions by maximizing cumulative rewards in an environment.",
        "negative_doc": "Mount Everest is the highest mountain peak above sea level on Earth located in the Himalayas."
    },
    {
        "question": "What mechanism do Transformers use to replace RNNs?",
        "positive_doc": "Transformers replace recurrent neural networks and LSTM networks with multi-head self-attention mechanisms.",
        "negative_doc": "Baking bread requires flour, water, yeast, and salt mixed and fermented properly."
    },
    {
        "question": "Why does RAG reduce hallucination?",
        "positive_doc": "RAG significantly reduces model hallucination by grounding generation in authoritative retrieved source documents.",
        "negative_doc": "Jupiter is the largest planet in our solar system and possesses a giant storm known as the Great Red Spot."
    },
    {
        "question": "What is a vector database used for?",
        "positive_doc": "Vector databases store high-dimensional dense vector embeddings and enable fast nearest-neighbor similarity search.",
        "negative_doc": "The Amazon rainforest produces vast amounts of oxygen and houses millions of species."
    },
    {
        "question": "What does Layer Normalization do in Transformers?",
        "positive_doc": "Layer Normalization stabilizes the hidden state dynamics in deep Transformers and accelerates training convergence.",
        "negative_doc": "The Pacific Ocean is the largest and deepest ocean basin on Earth."
    },
    {
        "question": "What is Deep Learning?",
        "positive_doc": "Deep Learning is a branch of machine learning based on artificial neural networks with multiple representation layers.",
        "negative_doc": "The human heart pumps oxygenated blood through arteries and veins throughout the body."
    }
]

SAMPLE_QA_DATA = [
    {
        "context": "Artificial Intelligence (AI) is the simulation of human intelligence processes by computer systems, including learning, reasoning, and self-correction.",
        "question": "What is Artificial Intelligence?",
        "answer": "Artificial Intelligence is the simulation of human intelligence processes by computer systems, including learning and reasoning.",
        "target_chunk_id": "ai_notes.txt_chunk_0000"
    },
    {
        "context": "Machine Learning is a subfield of artificial intelligence that focuses on building algorithms that learn patterns from data.",
        "question": "What is Machine Learning?",
        "answer": "Machine Learning is a subfield of AI focused on building systems that learn statistical patterns from data.",
        "target_chunk_id": "machine_learning_overview.txt_chunk_0000"
    },
    {
        "context": "The Transformer architecture was introduced in the seminal 2017 paper Attention Is All You Need by Vaswani et al.",
        "question": "Who introduced the Transformer architecture?",
        "answer": "The Transformer architecture was introduced by Vaswani et al. in the 2017 paper Attention Is All You Need.",
        "target_chunk_id": "transformer_architecture.txt_chunk_0000"
    },
    {
        "context": "Transformers replace recurrent neural networks with multi-head self-attention mechanisms to process all tokens simultaneously.",
        "question": "What mechanism do Transformers use?",
        "answer": "Transformers use multi-head self-attention mechanisms to process tokens in parallel.",
        "target_chunk_id": "transformer_architecture.txt_chunk_0000"
    },
    {
        "context": "Retrieval-Augmented Generation enhances Large Language Models by retrieving relevant documents from an external knowledge base.",
        "question": "What is RAG?",
        "answer": "Retrieval-Augmented Generation enhances language models by retrieving relevant documents from an external knowledge base.",
        "target_chunk_id": "rag_systems.txt_chunk_0000"
    },
    {
        "context": "A standard RAG pipeline consists of document ingestion, chunking, dense vector embedding, similarity search, and answer generation.",
        "question": "What are the core components of RAG?",
        "answer": "The core components of RAG are document ingestion, chunking, dense embedding, similarity search, and answer generation.",
        "target_chunk_id": "rag_systems.txt_chunk_0000"
    },
    {
        "context": "Supervised learning algorithms build predictive models from labeled datasets with known target outputs.",
        "question": "What is supervised learning?",
        "answer": "Supervised learning algorithms build predictive models from labeled datasets with known target outputs.",
        "target_chunk_id": "machine_learning_overview.txt_chunk_0000"
    },
    {
        "context": "Unsupervised learning discovers hidden patterns and representations in unlabeled data without target labels.",
        "question": "What is unsupervised learning?",
        "answer": "Unsupervised learning discovers hidden patterns and clusters in unlabeled data without target labels.",
        "target_chunk_id": "machine_learning_overview.txt_chunk_0000"
    },
    {
        "context": "Reinforcement learning trains autonomous agents to make sequences of decisions by maximizing cumulative rewards.",
        "question": "What is reinforcement learning?",
        "answer": "Reinforcement learning trains agents to make decision sequences by maximizing cumulative rewards.",
        "target_chunk_id": "machine_learning_overview.txt_chunk_0000"
    },
    {
        "context": "Vector databases store high-dimensional dense vector embeddings and enable fast similarity search.",
        "question": "What is a vector database?",
        "answer": "A vector database stores high-dimensional vector embeddings and enables fast similarity search.",
        "target_chunk_id": "vector_databases.txt_chunk_0000"
    },
    {
        "context": "Deep Learning is a branch of machine learning based on artificial neural networks with multiple representation layers.",
        "question": "What is Deep Learning?",
        "answer": "Deep Learning is a machine learning branch based on multi-layer artificial neural networks.",
        "target_chunk_id": "deep_learning_concepts.txt_chunk_0000"
    },
    {
        "context": "Layer Normalization stabilizes hidden state dynamics in deep Transformers and accelerates training convergence.",
        "question": "What is the purpose of Layer Normalization?",
        "answer": "Layer Normalization stabilizes hidden state dynamics and accelerates convergence in deep Transformers.",
        "target_chunk_id": "deep_learning_concepts.txt_chunk_0000"
    }
]

def prepare_sample_data():
    os.makedirs(DOCUMENTS_DIR, exist_ok=True)
    os.makedirs(TRAINING_DATA_DIR, exist_ok=True)

    # 1. Save sample text documents
    for doc in SAMPLE_DOCUMENTS:
        filepath = os.path.join(DOCUMENTS_DIR, doc["filename"])
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(doc["content"])
    print(f"[OK] Sample documents saved to: {DOCUMENTS_DIR}")

    # 2. Save retriever dataset
    retriever_file = os.path.join(TRAINING_DATA_DIR, "retriever_data.json")
    with open(retriever_file, "w", encoding="utf-8") as f:
        json.dump(SAMPLE_RETRIEVER_DATA, f, indent=2)
    print(f"[OK] Retriever training data saved to: {retriever_file}")

    # 3. Save QA dataset
    qa_file = os.path.join(TRAINING_DATA_DIR, "qa_pairs.json")
    with open(qa_file, "w", encoding="utf-8") as f:
        json.dump(SAMPLE_QA_DATA, f, indent=2)
    print(f"[OK] Generator QA training data saved to: {qa_file}")

if __name__ == "__main__":
    prepare_sample_data()
